[package]
name = "vorbis"
version = "0.0.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies.vorbisfile-sys]
git = "https://github.com/tomaka/vorbisfile-sys"

[dev-dependencies.openal-rs]
git = "https://github.com/bjz/openal-rs"
